version: "2"

services:
  app:
    build: src/
    container_name: app
    restart: always
    links:
      - mongodb:mongodb
    ports:
      - 3000:3000
      - 5858:5858
    volumes:
      - ./src:/opt/src
    environment:
      NODE_ENV: development

  mongodb:
    image: mongo:3.0.4
    container_name: mongodb
    ports:
      - 27017:27017
    command: --smallfiles --rest
